#12 add Commander search as a separate button
Kender2/swc-squadranking pull request #14
Opened 2016-12-30 00:18 UTC by spariev

Added commander search as a separate form. I was thinking about searching for both squads and commanders in `squadsearch` controller action, but case with redirect to squad page if only one squad found complicates everything. Anyway, it is up to you to decide how to do it best, hope my contribution will be of any use.

2016-12-30 09:08 UTC, Kender2 requested changes
Thanks for picking this up!

2016-12-30 09:08 UTC, Kender2 commented on resources/views/commandersearch.blade.php
> +                {!! $results->appends(['q' => request('q')])->render() !!}
This needs to be 'sq', otherwise the paging doesn't work.

2016-12-30 09:08 UTC, Kender2 commented on resources/views/commandersearch.blade.php
> +                            <td><a href="squad/{{$comm->squad->id}}">{!! \App\Squad::colorName($comm->squad->name) !!}</a></td>
Better to link to the members page with something like `{{ route('squadmembers', ['id' => $comm->squad->id]) }}`

2016-12-30 09:08 UTC, Kender2 commented on resources/views/commandersearch.blade.php
> +                            <td>{!! $comm->hqLevel !!}</td>
add `class="rank"` to get the nrs right aligned.

2016-12-30 09:08 UTC, Kender2 commented on app/Http/Controllers/SquadController.php
> +            $results = Commander::with('squad')->where('name', 'LIKE', '%' . $searchTerm . '%')->orderByRaw('name')->simplePaginate(100);
You can use `orderBy` here in stead of `orderByRaw`

2016-12-30 09:08 UTC, Kender2 commented on app/Http/Controllers/SquadController.php
> +            $results = Commander::with('squad')->where('name', 'LIKE', '%' . $searchTerm . '%')->orderByRaw('name')->simplePaginate(100);
100 commanders per page is a bit much. Use 20 like the squad search.

2016-12-30 09:08 UTC, Kender2 commented on app/Commander.php
> +        return $this->belongsTo('App\Squad', 'squadId');
Good catch!

2016-12-30 09:08 UTC, Kender2 commented on resources/views/nav.blade.php
> +            <form class="navbar-form navbar-right" role="search" method="get"
Yeah, this looks horrible in mobile. Insomniac's suggestion in https://github.com/Kender2/swc-squadranking/issues/12#issuecomment-269651029 might be a better approach.

2016-12-30 09:08 UTC, Kender2 commented on resources/views/commandersearch.blade.php
> +			<th>Level</th>
Indentation is off and I prefer 'HQ level'

2016-12-30 14:45 UTC, spariev commented
Thanks for you feedback, sorry for the code style, php is not my native language :) gonna try to fix everything over the weekend.
I also found another search with dropdown snippet, http://www.bootply.com/gWOb4RcY86 , which looks a bit better to me, will try to use it.

2017-01-04 16:48 UTC, MidgetAl commented
Wow ... does that mean this is doable now? I love reading through all of this stuff and realizing I have no clue what you guys are talking about.

2017-01-05 08:42 UTC, spariev commented
I decided to use snippet from here http://www.bootply.com/gWOb4RcY86 , looks fine to me :) .
Also moved both squadSearch() and commanderSearch() into common search() function.

2017-01-08 06:57 UTC, Kender2 commented on app/Http/Controllers/SquadController.php
> +                $searchType = $request->input('searchtype');
You may pass a default value as the second argument to the input method. This value will be returned if the requested input value is not present on the request

2017-01-08 06:57 UTC, Kender2 commented on app/Http/Controllers/SquadController.php
> +    public function search(Request $request)
I think it's probably wise to move the searches to a separate searchcontroller rather than having the squadcontroller deal with commanders too.

2017-01-08 06:57 UTC, Kender2 commented on resources/views/commandersearch.blade.php
> +    COMMANDER SEARCH
Since the search button uses "Players" I think this should say PLAYER SEARCH.
Or the other way around, as long as it's consistent :)

2017-01-08 07:59 UTC, Kender2 commented
You know what, I'll be working on the site anyway today. I'll merge in your changes into that.

2017-01-08 08:13 UTC, spariev commented
Yeah that probably would be faster as I won't have time until tomorrow
evening. Thanks!

On Jan 8, 2017 9:59 AM, "Kender2" <notifications@github.com> wrote:

> You know what, I'll be working on the site anyway today. I'll merge in
> your changes into that.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kender2/swc-squadranking/pull/14#issuecomment-271136778>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAAxBnd1cZO8tm3ffGTc1Bzmfs8y8saOks5rQJdRgaJpZM4LX7aJ>
> .
>

2017-01-08 10:58 UTC, merged